package serverapp.enums;

public enum Actions {
    LOGIN("login"),
    SAVEUSERS("saveUsers"),
    REGISTER("register"),
    LOGOUT("logout"),
    SCOREBOARD("scoreBoard"),
    DELETEACOUNT("deleteAcount"),
    CHANGENICKNAME("changeNickName"),
    CHAGEPASSWORD("changePassWord"),
    INVITETOGAME("inviteToGame"),
    STARTGAME("startGame"),
    SENDINITATION("sendInvitation"),
    BROADCASTINVITATION("broadCastInvitation"),
    INITIALIZEHEARINGSERVERSOCKET("initializeHearingServerSocket"),
    UNIQUEUSERNAME("uniqueUsername"),
    ACCEPTINVITATION("acceptInvitation"),
    REJECTINVITATION("REJECTINVITAION"),
    SENDREJECTION("sendRejection"),
    GETPANEDETAILS("getPaneDetails"),
    SELECTILE("selectTile"),
    GETUNITINFORMATION("getUnitInformation"),
    GetHexDetails("getHexDetails"),
    GetTerrainNames("getTerrainNames"),
    GETHexInWidth("getHexInWidth"),
    GETHexInHeight("getHexInHeight"),
    SELECTUNIT("selectUnit"),
    ISMYUNIT("isMyUnit"),
    GETAVAILABLEWORKS("getAvailableWorks"),
    ATTACKUNIT("attackUnit"),
    STARTMOVEMENT("startMovement"),
    DELETEUNIT("deletUnit"),
    PILLAGE("pillage"),
    ALERT("alert"),
    SLEEPUNIT("SLEEPUNIT"),
    FORTIFY("frtify"),
    WAKEDUP("wakeUp"),
    GARRISON("garrison"),
    SETUPFORRANGEATTACK("setUpSiegeForRangeAttack"),
    FORTIFYUNTILLHEAL("fortifyUntilHeal"),
    BUILDCITY("buildCity"),
    UNITLISTPANEL("unitListPanel"),
    getLastTechnology("getLastTechnology"),
    getAvailableTechsArray("getAvailableTechsArray"),
    changeResearch("changeResearch"),
    ISANACHIVEDTECK("ISANACHIVEDTECK"),
    getNotificationsTurns("getNotificationsTurns"),
    getNotifications("getNotifications"),
    militaryPanel("militaryPanel"),
    demographicScreen("demographicScreen"),
    cityScreen("cityScreen"),
    getPlayerCitiesNames("getPlayerCitiesNames"),

    cheatCityProduction("cheatCityProduction"),
    cheatGold("cheatGold"),
    cheatHappiness("cheatHappiness"),
    cheatPopulation("cheatPopulation"),
    cheatProduction("cheatProduction"),
    cheatScore("cheatScore"),
    cheatMP("cheatMP"),
    cheatRangedCombatStrength("cheatRangedCombatStrength"),
    cheatMeleeCombatStrength("cheatMeleeCombatStrength"),
    cheatCityFood("cheatCityFood"),
    cheatCityHitPoint("cheatCityHitPoint"),
    cheatTrophy("cheatTrophy"),
    initializePublicChat("initializePublicChat"),
    sendMessage("sendMessage"),
    updateMessages("updateMessages"),
    getOnlineUsers("getOnlineUsers"),
    startPrivateChat("startPrivateChat"),
    setSelectedCity("setSelectedCity"),
    presaleTiles("presaleTiles"),
    buyHex("buyHex"),
    citiesPanel("citiesPanel"),
    orderToWorker("orderToWorker"),
    changeTurn("changeTurn"),
    handelFogOfWarRemoverButton("handelFogOfWarRemoverButton"),
    CHANGETURNOFOTHEROLAYERS("CHANGETURNOFOTHEROLAYERS"),
    deleteMessage("deleteMessage"),
    editMessageButton("editMessage"),
    editMessageFinal("editMessageFinal"),
    startRoom("startRoom"),
    getAllFreinShipRequests("getAllFreinShipRequests"),
    getRejectedRequests("getRejectedRequests"),
    getAllFriendsNames("getAllFriendsNames"),
    sendFriendShipRequest("sendFriendShipRequest"),
    getPicUrl("getPicUrl"),
    DELETECITY("DLETECITY"),
    ADDCITYTOTERRITORY("ADDCITYTOTERRITORY"),
    unlockTechnology("unlockTechnology"),
    getAvailableBuildings("getAvailableBuildings"),
    buildBuilding("buildBuilding"),
    showHappiness("showHappiness"),
    setPicUrl("setPicUrl"),
    buyUnit("buyUnit"),
    makeUnit("makeUnit"),
    getTechnologyInfo("getTechnologyInfo"),
    getBuildingInfo("getBuildingInfo"),
    getImprovementNameOfWoorker("getImprovementNameOfWoorker"),
    playerMainInfo("playerMainInfo"),
    gameOver("gameOver"),
    acceptFriendship("acceptFriendship"),
    rejectFriendship("rejectFriendship"),
    updateScoreBoard("updateScoreBoard"),
    exit("exit"),
    LOCKINGCITIZENTOTILE("LOCKINGCITIZENTOTILE"),
    REMOVECITIZENFROMWORK("REMOVECITIZENFROMWORK"),
    showUnEmployedCitizen("showUnEmployedCitizen"),
    CITYATTACKTOUNIT("CITYATTACKTOUNIT"),
    getHealth("getHealth"),
    increaseHealth("increaseHealth"),
    getIsEnemy("getIsEnemy"),
    setIsEnemy("setIsEnemy");

    private final String character;

    Actions(String color) {
        this.character = color;
    }

    public String getCharacter() {
        return character;
    }
}

